preload = /home/liv/.config/hypr/wallpaper/lain_c.png
preload = /home/liv/.config/hypr/wallpaper/lain-long.png
wallpaper = DP-1, /home/liv/.config/hypr/wallpaper/lain_c.png
wallpaper = DP-2, /home/liv/.config/hypr/wallpaper/lain-long.png
