general {
    # Gaps between windows
    gaps_in = 5

    # Gaps between window and screen edge
    gaps_out = 7

    # Border width
    border_size = 1

    # Border colors
    col.active_border = rgb(383838) #<<active
    col.inactive_border = rgb(181818) #<<inactive

    # No touchy
    resize_on_border = false
    allow_tearing = false

    # Layout
    layout = scroller

}

# Border decoration

decoration {
    # Corner rounding
    rounding = 5

    # Change transparency of focused and unfocused windows

    active_opacity = 1.0
    inactive_opacity = .5

    # Blur

    blur {
        enabled = true
        size = 20
        passes = 3

        vibrancy = 0.2
    }
}
